application: ingress-notify
version: 2012-12-07
api_version: 1
runtime: python27
threadsafe: yes

inbound_services:
- mail
- xmpp_message

handlers:
- url: /_ah/mail/.+
  script: mail.APP

- url: /_ah/admin.*
  script: google.appengine.ext.admin.application
  secure: always
  login: admin

- url: /
  static_files: index.html
  upload: index.html
  secure: always
  login: required

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: main.APP
  secure: always
